/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fe696c64-ce24-42b5-8800-779b880815d5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_84mg2QwEZ",
    "aws_user_pools_web_client_id": "1lcls0qk85llnktet834gv0rdh",
    "oauth": {}
};


export default awsmobile;
